

use bank;
CREATE TABLE bank.receiver 
(
    rid integer not null auto_increment,
    BIC	varchar(300),
    bank	varchar(300),
    code	varchar(300),
    primary key(rid)
);

INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ABBLINBBXXX', 'AB BANK LIMITED', 'CHQB');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ACBLINBBXXX', 'ABHYUDAYA CO-OPERATIVE BANK LTD.', 'CORT');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ABNAINBBAHM', 'ABN AMRO BANK N.V.', 'HOLD');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ADCBINBBXXX', 'ABU DHABI COMMERCIAL BANK', 'INTC');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ALLAINBBXXX', 'ALLAHABAD BANK', 'PHOB');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ANDBINBBXXX', 'ANDHRA BANK', 'PHOI');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ADIAINBBXXX', 'ANTWERP DIAMOND BANK N.V.', 'PHON');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('AXISINBBXXX', 'AXIS BANK LIMITED', 'REPA');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BOFAIN4XMAA', 'BANK OF AMERICA, N.A. CHENNAI', 'SDVA');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BOFAIN4XCCU', 'BANK OF AMERICA, N.A. KOLKATA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BBKUINBBXXX', 'BANK OF BAHRAIN AND KUWAIT B.S.C.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BARBINBBXXX', 'BANK OF BARODA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BCEYIN5MXXX', 'BANK OF CEYLON', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BKIDINBBXXX', 'BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('MAHBINBBAHM', 'BANK OF MAHARASHTRA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('NOSCINBBBLR', 'BANK OF NOVA SCOTIA, THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BOTKIN5MXXX', 'BANK OF TOKYO-MITSUBISHI UFJ, LTD., THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BARCINBBMUM', 'BARCLAYS BANK PLC', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BNPAINBBAHM', 'BNP PARIBAS INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CNRBINBBXXX', 'CANARA BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CSYBIN55XXX', 'CATHOLIC SYRIAN BANK LTD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CBININBBLAL', 'CENTRAL BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CTCBINDDXXX', 'CHINATRUST COMMERCIAL BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CITIINBXBLR', 'CITIBANK N.A.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CIUBIN5MXXX', 'CITY UNION BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CCILINBBXXX', 'CLEARING CORPORATION OF INDIA LTD, THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CORPINBBXXX', 'CORPORATION BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('DBSSINBBIBD', 'DBS BANK LTD, MUMBAI BRANCH', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BKDNINBBXXX', 'DENA BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('DEUTINBBBGL', 'DEUTSCHE BANK AG', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('DCBLINBB036', 'DEVELOPMENT CREDIT BANK LTD.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('DLXBINBBKPM', 'DHANALAKSHMI BANK LTD, THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('EIBIINBBXXX', 'EXPORT-IMPORT BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('FDRLINBBXXX', 'FEDERAL BANK LIMITED, THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('FIRNINBBXXX', 'FIRSTRAND BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('HDFCINBBAHM', 'HDFC BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('HSBCINBBBGE', 'HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('ICICINBB024', 'ICICI BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('IBKLINBBXXX', 'IDBI BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('IDIBINBBXXX', 'INDIAN BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('IOBAINBBXXX', 'INDIAN OVERSEAS BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('INDBINBBXXX', 'INDUSIND BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('VYSAINBBAHD', 'ING VYSYA BANK LTD.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('JAKAINBBAGR', 'JAMMU AND KASHMIR BANK LTD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('CHASINBXTRO', 'JPMORGAN CHASE BANK, N.A.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('VTBRINDDXXX', 'JSC VTB BANK, NEW DELHI BRANCH', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('KARBINBBBNG', 'KARNATAKA BANK LTD.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('KVBLINBBADI', 'KARUR VYSYA BANK LTD., THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('KKBKINBBCPC', 'KOTAK MAHINDRA BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('KRTHINBBXXX', 'KRUNG THAI BANK PUBLIC COMPANY LTD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('LAVBINBB114', 'LAKSHMI VILAS BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('MSCIINBBXXX', 'MAHARASHTRA STATE CO-OPERATIVE BANK LTD., THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('MSHQINBBXXX', 'MASHREQ BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('MHCBINBBXXX', 'MIZUHO CORPORATE BANK LTD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('MSMBINBXXXX', 'MORGAN STANLEY INDIA COMPANY PVT LTD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('OIBAINBBXXX', 'OMAN INTERNATIONAL BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('GTBKINBBXXX', 'ORIENTAL BANK OF COMMERCE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('PSIBINBB020', 'PUNJAB AND SIND BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('PUNBINBBXXX', 'PUNJAB NATIONAL BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('RBISINBBXXX', 'RESERVE BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SRCBINBBAUR', 'SARASWAT CO-OPERATIVE BANK LTD., THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SBCLINBBXXX', 'SBI COMMERCIAL AND INTERNATIONAL BANK LTD.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SHBKINBBXXX', 'SHINHAN BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SIDBINBBCBB', 'SMALL INDUSTRIES DEVELOPMENT BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SOGEINBBBLR', 'SOCIETE GENERALE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BSONINCCXXX', 'SONALI BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SOININ55179', 'SOUTH INDIAN BANK LTD., THE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SCDIIN51XXX', 'SPARK CAPITAL ADVISORS (INDIA) PRIVATE LTD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SCBLINBBMDS', 'STANDARD CHARTERED BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SBBJINBBXXX', 'STATE BANK OF BIKANER AND JAIPUR', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SBHYINBBXXX', 'STATE BANK OF HYDERABAD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SBININBBXXX', 'STATE BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('STININBBXXX', 'STATE BANK OF INDORE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('STCBINBXNPT', 'STATE BANK OF MAURITIUS LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SBMYINBBXXX', 'STATE BANK OF MYSORE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('STBPINBBXXX', 'STATE BANK OF PATIALA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SBTRINBBXXX', 'STATE BANK OF TRAVANCORE', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SYNBINBBXXX', 'SYNDICATE BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('TMBLINBBCHE', 'TAMILNAD MERCANTILE BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BRAJINBBARA', 'THE BANK OF RAJASTHAN LTD.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('BCMLINBBXXX', 'THE BHARAT CO-OPERATIVE BANK (MUMBAI) LTD', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('COSDINBBXXX', 'THE COSMOS CO-OPERATIVE BANK LTD.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('KALUINAAXXX', 'THE KALUPUR COMMERCIAL CO-OPERATIVE BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('SVCBINBBBLR', 'THE SHAMRAO VITHAL CO-OPERATIVE BANK LIMITED', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('TCILINBBXXX', 'THOMAS COOK (INDIA) LTD.', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('UBSWINBBXXX', 'UBS AG', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('UCBAINBBXXX', 'UCO BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('UBININBBXXX', 'UNION BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('UTBIINBBECB', 'UNITED BANK OF INDIA', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('VIJBINBBXXX', 'VIJAYA BANK', '');
INSERT INTO bank.receiver (BIC,bank,code) VALUES ('QWERTYUIQWE', 'QWERTY BANK LIMITED','' );
ALTER TABLE receiver ADD rid int NOT NULL AUTO_INCREMENT primary key;
select * from receiver;